language: ruby
rvm:
- 1.9.3
install:
- bash -x travis.sh install
script:
- bash -x travis.sh script
after_success:
- bash -x travis.sh after_success
env:
  global:
    secure: UzSCIpYgDMqcA7zqUDzCExOr13GGvTdJYaPMyGw/BKdkEJoVzpsBAe2xkP26YLttEXxM74fC7vakWgU3I8wgcXEGfVb9hEu5BvYgEuOIubtzkkCjS72duN5SOiMQKI/mE/UaJxSoQEa1M+ZT+2aBmoZpt0vHe5TKRkU8lntnmoc=
